# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: 'Actions Cache 4.4.0'

on:
  workflow_dispatch:

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        # This might not be required?
        # repo-token: ${{ secrets.GITHUB_TOKEN }}
        operations-per-run: 100 # This should be temporary.
        # exempt-issue-labels: ehancement,good first issue
        #exempt-issue-labels: '!stale'
        stale-issue-label: 'ActionsCache'
        stale-pr-label: 'ActionsCache'
        days-before-issue-stale: 1
        days-before-pr-stale: 1
        stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            any activity in the last 60 days. It will be closed in 7 days if no further
            activity occurs. Please feel free to leave a comment if you believe the issue
            is still relevant.
        close-issue-message: >
            This issue has been automatically closed due to inactivity.