name: "Issue 1132"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "12 3 * * *"  # arbitrary time not to DDOS GitHub
# permissions:
#   pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR was marked stale due to lack of activity. It will be closed in 7 days.'
          close-pr-message: 'Closed as inactive. This is from issue 1132'
          exempt-pr-labels: 'release:after-ga'
          days-before-stale: 2
          days-before-close: 2